### ISSUE TITLE
how to train my data?

### ISSUE THREAD

**Issue by niliuxi** [dbolya/yolact#184]
I have got the json file now, what do I need to modify to train my data?Looking forward to your reply

**Comment by dbolya** [comment]
The steps are in the readme here: https://github.com/dbolya/yolact#custom-datasets.

**Comment by sainatarajan** [comment]
Refer to this issue #155. Your keyerror issue looks similar to the one I faced.

**Comment by dbolya** [comment]
Moving the discussion over here:

> > @niliuxi Again, own thread, but if you are restricting COCO to just person for instance, there are a couple pitfalls to avoid:
> > 
> > The proper way to specify a tuple of 1 element in python is ('person',). If you do ('person') that will resolve to a list of each character, which is not what you want (so check your class_names).
> > You have to modify the coco jsons to remove all annotations that are not for your given class. So in the person case, it would be to remove all 'annotations' elements with ann['category_id'] != 1 (for any other class, use that class's id).
> > Finally, if the class you're using isn't person, set label_map to { 1: id } where id is the category id that you didn't remove above (setting it to None will automatically generate { 1: 1 }).
> 
> I don't quite understand the second point you said. You are referring to the json file in the annotations folder?There is still a bit of confusion. I want to ask you. When I use labelme for labeling, different people are named person1. person2,..., is this naming method correct, so I named my category id>1

I mean the generated json, yes. Check to see if the annotations array has any object with `category_id != 1`. I'm pretty sure labelme doesn't create a new class for each person in an image, so there shouldn't be.

Also, earlier you said you were using COCO? Which is it? Are you using the COCO annotations or your own dataset?

**Comment by niliuxi** [comment]
> Moving the discussion over here:
> 
> > > @niliuxi Again, own thread, but if you are restricting COCO to just person for instance, there are a couple pitfalls to avoid:
> > > The proper way to specify a tuple of 1 element in python is ('person',). If you do ('person') that will resolve to a list of each character, which is not what you want (so check your class_names).
> > > You have to modify the coco jsons to remove all annotations that are not for your given class. So in the person case, it would be to remove all 'annotations' elements with ann['category_id'] != 1 (for any other class, use that class's id).
> > > Finally, if the class you're using isn't person, set label_map to { 1: id } where id is the category id that you didn't remove above (setting it to None will automatically generate { 1: 1 }).
> > 
> > 
> > I don't quite understand the second point you said. You are referring to the json file in the annotations folder?There is still a bit of confusion. I want to ask you. When I use labelme for labeling, different people are named person1. person2,..., is this naming method correct, so I named my category id>1
> 
> I mean the generated json, yes. Check to see if the annotations array has any object with `category_id != 1`. I'm pretty sure labelme doesn't create a new class for each person in an image, so there shouldn't be.
> 
> Also, earlier you said you were using COCO? Which is it? Are you using the COCO annotations or your own dataset?

If I mark different people as person1, person2, the category will be displayed like this
 "categories": [
        {
            "supercategory": "Cancer",
            "id": 1,
            "name": "person1"
        },
        {
            "supercategory": "Cancer",
            "id": 2,
            "name": "person2"
        }]
I am using my own dataset and converting it to coco's json file via labelme2coco

**Comment by dbolya** [comment]
Oh that's not good, they all should be the same category with id=1. Might have to convert them manually? Or maybe you didn't configure labelme exactly right (though the easiest now would just be to fix the mistake manually by removing all the extra categories and setting all annotations to have category_id=1).

**Comment by niliuxi** [comment]
> Oh that's not good, they all should be the same category with id=1. Might have to convert them manually? Or maybe you didn't configure labelme exactly right (though the easiest now would just be to fix the mistake manually by removing all the extra categories and setting all annotations to have category_id=1).

Thank you, I will try it. In addition, I would like to ask, should it be marked as person1, person2, or person? I see this https://github.com/wkentaro/labelme/tree/master/examples/instance_segmentation URL as indicated by person1, person2.

**Comment by dbolya** [comment]
I haven't used labelme, so I don't know. But I will point out that for the example where they labeled each `person-1`, `person-2`, etc., the command they used included `--labelflags '{.*: [occluded, truncated], person-\d+: [male]}'`, which indicates that they mapped all `person-<digit>` to `male`. Maybe this is the step that you missed?

**Comment by niliuxi** [comment]
I will try ，thank you very much！ @dbolya

**Comment by niliuxi** [comment]
I've modified the JSON file for coco conversion. The category ID is already 1, but now I have a new problem. I hope you can help me look at it, as follows: I found that my t time is 0, and my CUDA does not overflow. I don't know why this exception is reported.
Multiple GPUs detected! Turning off JIT.
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
Initializing weights...
Begin training!

/home/uroot/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/nn/parallel/_functions.py:61: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn('Was asked to gather along dimension 0, but all '
[  0]       0 || B: 6.109 | C: 11.741 | M: 5.075 | S: 1.021 | T: 23.947 || ETA: 0:00:00 || timer: 17.604

Computing validation mAP (this may take a while)...

Traceback (most recent call last):
  File "/home/uroot/niliuxi_yolact/train.py", line 384, in <module>
    train()
  File "/home/uroot/niliuxi_yolact/train.py", line 307, in train
    compute_validation_map(yolact_net, val_dataset)
  File "/home/uroot/niliuxi_yolact/train.py", line 377, in compute_validation_map
    eval_script.evaluate(yolact_net, dataset, train_mode=True)
  File "/home/uroot/niliuxi_yolact/eval.py", line 876, in evaluate
    prep_metrics(ap_data, preds, img, gt, gt_masks, h, w, num_crowd, dataset.ids[image_idx], detections)
  File "/home/uroot/niliuxi_yolact/eval.py", line 384, in prep_metrics
    classes, scores, boxes, masks = postprocess(dets, w, h, crop_masks=args.crop, score_threshold=args.score_threshold)
  File "/home/uroot/niliuxi_yolact/layers/output_utils.py", line 102, in postprocess
    masks = F.interpolate(masks.unsqueeze(0), (h, w), mode=interpolation_mode, align_corners=False).squeeze(0)
  File "/home/uroot/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/nn/functional.py", line 2518, in interpolate
    return torch._C._nn.upsample_bilinear2d(input, _output_size(2), align_corners)
RuntimeError: CUDA out of memory. Tried to allocate 8.94 GiB (GPU 0; 10.76 GiB total capacity; 771.62 MiB already allocated; 8.88 GiB free; 218.38 MiB cached)

Process finished with exit code 1

**Comment by niliuxi** [comment]
When I set the batch size to 2, there will be CUDA out of memory. So when I set the batch size to 1, I will report the following error. I hope I can get your help. In addition, I find that my t time is zero.

Multiple GPUs detected! Turning off JIT.
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
Initializing weights...
Begin training!

Traceback (most recent call last):
  File "/home/uroot/niliuxi_yolact/train.py", line 384, in <module>
    train()
  File "/home/uroot/niliuxi_yolact/train.py", line 259, in train
    losses = criterion(out, wrapper, wrapper.make_mask())
  File "/home/uroot/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/uroot/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 152, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/uroot/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 162, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/uroot/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 85, in parallel_apply
    output.reraise()
  File "/home/uroot/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/_utils.py", line 385, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/home/uroot/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "/home/uroot/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/uroot/niliuxi_yolact/layers/modules/multibox_loss.py", line 141, in forward
    pos_idx = pos.unsqueeze(pos.dim()).expand_as(loc_data)
RuntimeError: The expanded size of the tensor (19248) must match the existing size (9624) at non-singleton dimension 1.  Target sizes: [1, 19248, 4].  Tensor sizes: [1, 9624, 1]


Process finished with exit code 1

**Comment by dbolya** [comment]
First of all, keep your batch size at 8. Your problem is not batch size. Instead, your problem is your image size. During evaluation, the code outputs annotations at the same size as the labelled data for fairness's sake. However, it looks like your images are very big so this actually takes a whole bunch of memory and overloads your GPU.

What size images are you using for your dataset, and can you try reducing their size to 550x550? (You'll also have to reduce the size of your bboxes and masks too).

**Comment by niliuxi** [comment]
Yes, my picture is very big. Now I will reduce it to 550. Thank you again. It's very helpful!

**Comment by agneevguin** [comment]
Reducing the image size would mean changing all the json files as well. Is this needed?

**Comment by niliuxi** [comment]
Need------------------ 原始邮件 ------------------
发件人: "agneevguin"<notifications@github.com>
发送时间: 2019年10月23日(星期三) 下午3:22
收件人: "dbolya/yolact"<yolact@noreply.github.com>;
抄送: "niliuxi"<530562700@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [dbolya/yolact] how to train my data? (#184)



Reducing the image size would mean changing all the json files as well. Is this needed?
 
&mdash;

**Comment by sainatarajan** [comment]
@agneevguin That would be a tremendous amount of work. It would require to re-calculate all the bounding box coordinate points too, to suit the newly scaled images.

**Comment by dbolya** [comment]
I can make a utility script for it if you guys want--it's not actually that difficult (if you're not doing it by hand, that is). For each annotation, load the old image size as iw and ih, and set `sw, sh = (550 / iw, 550 / ih)`. Then the new box will be `[sw * x, sh * y, sw * w, sh * h]`. The new segmentation would just be
```[[(sw, sh)[idx % 2] * x for idx, x in enumerate(p)] for p in polygon]```. (Warning, these are untested).

If I implemented the same as "data augmentaton" (really gt "augmentation"), then it would just be the same code except done on the fly which would be slow.

**Comment by niliuxi** [comment]
@dbolya Thank you,I will try.
Now,I have encountered this problem:
ImportError: libcudart.so.9.0: cannot open shared object file: No such file or directory

I tried to modify：
     export PATH=$PATH:/usr/local/cuda-10.0/bin
     export LIBRARY_PATH=$LIBRARY_PATH: /usr/local/cuda-10.0/lib64
     source /etc/profile , but still not.

**Comment by dbolya** [comment]
@niliuxi Uhh not sure how that happened? Sounds like you need to reinstall pytorch, since pytorch ships with those automatically.

**Comment by niliuxi** [comment]
I am using the connection server, when I click run directly to make the program run without problems, but when I use the SSH session will report this error.

**Comment by dbolya** [comment]
Are you sure you have your environments set up in your SSH session the same as your offline sessions? By that I mean, did you forget to activate your python environment or something?

**Comment by niliuxi** [comment]
I have been using SSH session, not offline, the difference between the two is that one is directly click on the program right click on the run, the other is to use the terminal, because I need to run python eval.py --output_coco_json

**Comment by dbolya** [comment]
Ok that's weird. Are you sure you're using the same version of python as both your default run option and in the console? Make sure it's the exact same installation of python.

**Comment by niliuxi** [comment]
I confirm that it is the same,They use the same one for the remote server.

**Comment by dbolya** [comment]
So what do you mean by "when I click run directly to". Where are you clicking run here? What environment are you using, and how were you specifying the other params required to run any of the scripts? Sorry, I'm not sure exactly what you mean so can you detail your process of running each way in detail?

**Comment by niliuxi** [comment]
I am using pycharm software. When I put this project into pycharm, I right click on the eval.py file and it will run. I can run it at this time. The parameters are all used. The default parameters. But when I want to modify the parameters, I can only do it through the terminal, and then the problem I mentioned above appears.

**Comment by dbolya** [comment]
Okay, how about instead of passing parameters in, you just modify the default ones? They're located at the top of eval.py starting from ~line 40. Actually, it might be easier if you just set the parameters in code, which you can do somewhere like here:
https://github.com/dbolya/yolact/blob/530415ff8a3f8f97b8deb58508ea74c84ea147b2/eval.py#L124
And then just add
```
    args.output_coco_json = True
    args.trained_model = 'weights/yolact_my_model.pth'
```
etc.

**Comment by niliuxi** [comment]
Thanks a lot.

**Comment by jyliu-dn** [comment]
That is so weird. 
When I set the batch_size =5, this problem occurs, but if it is set to 8, that is OK.

**Comment by dbolya** [comment]
@jyliu-dn Which problem? (Also you might want to make an new issue)

**Comment by agneevguin** [comment]
@dbolya is it possible to add a separate utility script to read the images and modify the jsons. This is to resize and generate bounding boxes and segmentations for the json files. I believe it would be quite useful to train large amounts of data.

**Comment by dbolya** [comment]
@agneevguin You mean to resize all images, boxes, and segmentation masks in the data to 550x550? I believe other people were wanting that as well, so I can add that to the TODO.

**Comment by jyliu-dn** [comment]
Thank you very much for receiving your reply.
The question I mentioned is not a new one, but a question raised by @niliuxi.
which is:
RuntimeError: The expanded size of the tensor (19248) must match the existing size (9624) at non-singleton dimension 1. Target sizes: [1, 19248, 4]. Tensor sizes: [1, 9624, 1]

It is occurs on my server(GeForce GTX 1080 * 4) when I set the batch_size =5,  but not occurs when I set the batch_size =8;
When I used my computer(with GeForce GTX 1080 * 1), batch_size =5 is OK to run the train.py, but batch_size =8 not.(in my computer, this question not occurs, it is just cant run the train.py)
The information I used is same in both the server and the computer, as follows:
dataset:         coco2017
python3:       3.5.2
pytorch:        1.1.0
torchvision:   0.1.9

**Comment by dbolya** [comment]
@jyliu-dn Your batch size should be evenly divisible by your number of GPUs. For 4 GPUs, pull the latest master branch (there's a bug fix), and train with batch size 32.

**Comment by jyliu-dn** [comment]
My server's GPU memory has only 8G, I tried it is OK just when the batch size is set to 24.
Thanks a lot.

**Comment by dbolya** [comment]
@jyliu-dn Yup 24 should work perfectly fine as well (6 images / gpu)

**Comment by agneevguin** [comment]
> @agneevguin You mean to resize all images, boxes, and segmentation masks in the data to 550x550? I believe other people were wanting that as well, so I can add that to the TODO.

Thanks a lot. :)

**Comment by jyliu-dn** [comment]
> @jyliu-dn Yup 24 should work perfectly fine as well (6 images / gpu)

Thanks a lot. ^_^

**Comment by agneevguin** [comment]
> @agneevguin You mean to resize all images, boxes, and segmentation masks in the data to 550x550? I believe other people were wanting that as well, so I can add that to the TODO.

I have a question here. 
The annotations are loaded into the memory from the pycocotools packages. 
So isn't it better that we already rescale the images while loading them or do you have any other augmentation suggestion in runtime?

**Comment by dbolya** [comment]
@agneevguin Currently the rescaling is done after all the data augmentation is finished. This is better because data augmentation can work with a higher resolution, but these people were having issues with running out of RAM / incredibly slow augmentation due to using huge images. So it would be better in that case to downsample offline so that you don't need to use as much memory / time during training.

**Comment by ShawnNew** [comment]
Hi @dbolya ,

I just used basic configuration to train on my own dataset (which is in coco format), and I only got around 20 MAP in both box and mask perspectives (30+ epochs).

I think the network may not be converged but I haven't seen some increase for epochs.

What do you suggest to improve the performance?

Thanks.

**Comment by hande6688** [comment]
> > 哦，这不好，它们都应该是id = 1的同一类别。可能必须手动转换它们？或者，也许您没有正确配置Labelme（尽管现在最简单的方法是通过删除所有额外的类别并将所有注释设置为category_id = 1来手动修复错误）。
> 
> 谢谢，我会尝试的。另外，我想问一下，应将其标记为person1，person2还是person？我看到此https://github.com/wkentaro/labelme/tree/master/examples/instance_segmentation URL，如person1，person2所示。

@niliuxi 
How to label a single category with labelme and instance segmentation? There are cat, cat, cat, cat0, cat1, cat2 or cat-0, cat-1, cat-2, etc. which annotation method is used?thank you!

I use cat-0, cat-1, cat-2 for annotation, and use labelme2coco to convert annotations.json, where the annotation is [], what's the matter?

**Comment by hande6688** [comment]
> 我没有使用过labelme，所以我不知道。但我会指出，对于其中它们每一个标记的例子`person-1`，`person-2`等等，指令他们使用包括`--labelflags '{.*: [occluded, truncated], person-\d+: [male]}'`，这可能表明它们映射的所有`person-<digit>`对`male`。也许这是您错过的步骤？

How to label a single category with labelme and instance segmentation? There are cat, cat, cat, cat0, cat1, cat2 or cat-0, cat-1, cat-2, etc. which annotation method is used?thank you!

I use cat-0, cat-1, cat-2 for annotation, and use labelme2coco to convert annotations.json, where the annotation is [], what's the matter?
